# SECTION Docker Compose File

version: '3.7'

x-common-variables: &common-variables
  MYSQL_USER: website_user
  MYSQL_PASSWORD: 1234ba
  MYSQL_DATABASE: website_db
  ANGULAR_APP_SERVER_PORT: 8000
  CHECK_SERVER_PORT: 3000

services:

  client:
    container_name: a11y-tool-app-client
    build:
      context: .
      dockerfile: DockerfileProduction
    depends_on:
      - server
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      #- '80:80' for Produktion Mode
      - '4201:4200'

  mysql:
    container_name: a11y-tool-app-database
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/website.sql:/docker-entrypoint-initdb.d/websites.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2-fpm-alpine
    container_name: a11y-tool-app-phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always

  server:
    container_name: a11y-tool-app-server
    build: ./server
    depends_on:
      - mysql
    expose:
      - 8000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 8000:8000
    volumes:
      - ./server/app
    links:
      - mysql
    command: npm start

  checks:
    container_name: a11y-tool-app-checks
    build: ./checks
    depends_on:
      - mysql
      - server
    environment:
      <<: *common-variables
      SERVER_HOST_IP: server
    ports:
      - 3000:3000
    volumes:
      - ./checks/app
    links:
      - server
    command: npm start

# !SECTION
